[tool.poetry]
name = "interop_clients"
version = "0.1.0"
description = "Alternative interop clients for AUVSI SUAS"
authors = ["NC State Aerial Robotics Club <aerialroboticsclub@ncsu.edu>"]

[tool.poetry.dependencies]
python = "3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
