[tool.black]
line-length = 79
include = '\.pyi?$'

[tool.poetry]
name = "interop_clients"
version = "0.1.0"
description = "Alternative interop clients for AUVSI SUAS"
authors = ["NC State Aerial Robotics Club <aerialroboticsclub@ncsu.edu>"]

[tool.poetry.dependencies]
python = "^3.6"
ARC = { git = "ssh://gitea/ARC/core.git" }
pyzmq = "^18.1.1"
GDAL = { version = "^3.0.4", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = "^19.3b0"
flake8 = "^3.7.9"
isort = "^4.3.21"
mypy = "^0.761"
flake8-bugbear = "^20.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
